networks:
  dev:

services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"  # Ключевая строка!
    networks:
      - dev
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  minio-data: